/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Guilherme
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesquisarLivro = new javax.swing.JButton();
        btnPesquisarLeitor = new javax.swing.JButton();
        btnAdicionarLivro = new javax.swing.JButton();
        btnAdicionarLeitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPesquisarLivro.setText("Pesquisar Livro");
        btnPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLivroActionPerformed(evt);
            }
        });

        btnPesquisarLeitor.setText("Pesquisar Leitor");
        btnPesquisarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLeitorActionPerformed(evt);
            }
        });

        btnAdicionarLivro.setText("Adicionar Livro");
        btnAdicionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarLivroActionPerformed(evt);
            }
        });

        btnAdicionarLeitor.setText("Adicionar Leitor");
        btnAdicionarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarLeitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(139, 139, 139)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnPesquisarLeitor)
                                                        .addComponent(btnPesquisarLivro,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 113,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnAdicionarLivro,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 113,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(btnAdicionarLeitor)))
                                .addContainerGap(148, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnPesquisarLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarLeitor)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdicionarLivro)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdicionarLeitor)
                                .addContainerGap(105, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPesquisarLivroActionPerformed
        new PesquisarLivro().setVisible(true); // TODO add your handling code here:
    }// GEN-LAST:event_btnPesquisarLivroActionPerformed

    private void btnPesquisarLeitorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPesquisarLeitorActionPerformed
        new PesquisarLeitor().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_btnPesquisarLeitorActionPerformed

    private void btnAdicionarLivroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdicionarLivroActionPerformed
        new AdicionarLivro().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_btnAdicionarLivroActionPerformed

    private void btnAdicionarLeitorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdicionarLeitorActionPerformed
        new AdicionarLeitor().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_btnAdicionarLeitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarLeitor;
    private javax.swing.JButton btnAdicionarLivro;
    private javax.swing.JButton btnPesquisarLeitor;
    private javax.swing.JButton btnPesquisarLivro;
    // End of variables declaration//GEN-END:variables
}